services:
  mongodb:
    image: mongo:latest
    container_name: code-ide-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: code-ide

  redis:
    image: redis/redis-stack
    container_name: code-ide-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: code-ide-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb+srv://ritesh:ritesh9122@ide.wco15ph.mongodb.net/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/usr/src/app # Mount entire project
      - /usr/src/app/node_modules
    command: npm run dev # Nodemon handles restart automatically
  app2:
    build: .
    container_name: code-ide-backendaa
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb+srv://ritesh:ritesh9122@ide.wco15ph.mongodb.net/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/usr/src/app # Mount entire project
      - /usr/src/app/node_modules
    command: npm run dev # Nodemon handles restart automatically

volumes:
  mongodb_data:
  redis_data:
